/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AdminCurriculumRouteImport } from './routes/admin.curriculum'
import { Route as BatchBatchIdCurriculumRouteImport } from './routes/batch.$batchId.curriculum'
import { Route as PaceBatchIdGroupIdRouteImport } from './routes/pace.$batchId.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/admin/curriculum',
  path: '/admin/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdCurriculumRoute = BatchBatchIdCurriculumRouteImport.update({
  id: '/batch/$batchId/curriculum',
  path: '/batch/$batchId/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const PaceBatchIdGroupIdRoute = PaceBatchIdGroupIdRouteImport.update({
  id: '/pace/$batchId/$groupId',
  path: '/pace/$batchId/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/batch/$batchId/curriculum': typeof BatchBatchIdCurriculumRoute
  '/pace/$batchId/$groupId': typeof PaceBatchIdGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/batch/$batchId/curriculum': typeof BatchBatchIdCurriculumRoute
  '/pace/$batchId/$groupId': typeof PaceBatchIdGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/batch/$batchId/curriculum': typeof BatchBatchIdCurriculumRoute
  '/pace/$batchId/$groupId': typeof PaceBatchIdGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/admin/curriculum'
    | '/batch/$batchId/curriculum'
    | '/pace/$batchId/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/admin/curriculum'
    | '/batch/$batchId/curriculum'
    | '/pace/$batchId/$groupId'
  id:
    | '__root__'
    | '/'
    | '/unauthorized'
    | '/admin/curriculum'
    | '/batch/$batchId/curriculum'
    | '/pace/$batchId/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AdminCurriculumRoute: typeof AdminCurriculumRoute
  BatchBatchIdCurriculumRoute: typeof BatchBatchIdCurriculumRoute
  PaceBatchIdGroupIdRoute: typeof PaceBatchIdGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/admin/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId/curriculum': {
      id: '/batch/$batchId/curriculum'
      path: '/batch/$batchId/curriculum'
      fullPath: '/batch/$batchId/curriculum'
      preLoaderRoute: typeof BatchBatchIdCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pace/$batchId/$groupId': {
      id: '/pace/$batchId/$groupId'
      path: '/pace/$batchId/$groupId'
      fullPath: '/pace/$batchId/$groupId'
      preLoaderRoute: typeof PaceBatchIdGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AdminCurriculumRoute: AdminCurriculumRoute,
  BatchBatchIdCurriculumRoute: BatchBatchIdCurriculumRoute,
  PaceBatchIdGroupIdRoute: PaceBatchIdGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
